WebApplication1/Models/ErrorViewModel.cs
using System;

namespace Solution.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/BaseController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;


namespace EFMovie.Web.Controllers
{
    public enum AlertType { success, danger, warning, info };

    public class BaseController : Controller
    {
        public void Alert(string message, AlertType type = AlertType.info)
        {
            TempData["Alert.Message"] = message;
            TempData["Alert.Type"] = type.ToString();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Solution.Web.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/RecordController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Xml.Serialization;
using EFMovie.Web.Controllers;
using Microsoft.AspNetCore.Mvc;
using Numbers.Data.Models;
using Numbers.Data.Service;
using Solution.Web.Models;


namespace WebApplication1.Controllers
{
    public class RecordController : BaseController
    {

        private readonly NumbersService svc;

        public RecordController()
        {
            svc = new NumbersService();
        }

        public ViewResult Index(string order = null)
        {
            var records = svc.GetAllRecords(order);

            return View(records);
        }

        public ViewResult GetRecord(int id)
        {
            var record = svc.GetRecord(id);
            var records = svc.GetAllRecords("Ascending");
            if (record==null)
            {
                Alert("Numbers not found", AlertType.warning);
                return View(nameof(Index), records);
            }
            return View(record);
        }

        public IActionResult Create()
        {
            return View();
        }

        public IActionResult Export(string order)
        {

            var records = svc.GetAllRecords("Ascending");

            if (order == "Descending")
            {
                records = svc.GetAllRecords("Descending");
            }

            if (records.Count()==0)
            {
                Alert("The database is empty, there is no data to export!", AlertType.warning);
                return View(nameof(Index),records);
            }

            try
            {
                XmlSerializer xs = new XmlSerializer(typeof(Record));
                TextWriter txtWriter = new StreamWriter("OrderedNumbers.xml");

                foreach (var r in records)
                {
                    xs.Serialize(txtWriter, r);
                }

                txtWriter.Close();
                Alert("Output successful, see file OrderedNumbers.xml", AlertType.success);
                return View(nameof(Index), records);

            } catch (Exception)
            {
                Alert("Output to XML file failed!", AlertType.warning);
                return View(nameof(Index), records);
            }
        }

        [HttpPost]
        public IActionResult Create([Bind("Numbers,TimeToSort,Order")] Record r)
        {
            var numbersString = r.Numbers;
            var intList = new List<int>();
            var stringsList = new List<string>();
            try
            {
                numbersString = r.Numbers.Trim();

                stringsList = numbersString.Split(' ').ToList();
                intList = new List<int>();
                for (int i = 0; i < stringsList.Count; i++)
                {
                    var stringnum = stringsList[i];
                    var temp = Convert.ToInt32(stringnum);
                    intList.Add(temp);
                }

            } catch ( Exception )
            {
                Alert("Invalid input: please enter integers only, separated by one space", AlertType.warning);
                return View(nameof(Create));          
            }

            IEnumerable sorted = intList;
            long elapsedTicks=0;

            if (r.Order == Order.Ascending)
            {
                Stopwatch stopWatch = new Stopwatch();
                stopWatch.Start();
                sorted = intList.OrderBy(s => s);
                stopWatch.Stop();
                elapsedTicks = stopWatch.ElapsedTicks;
            }

            if (r.Order == Order.Descending)
            {
                Stopwatch stopWatch2 = new Stopwatch();
                stopWatch2.Start();
                sorted = intList.OrderByDescending(s => s);
                stopWatch2.Stop();
                elapsedTicks = stopWatch2.ElapsedTicks;
            }

            string output = "";

            foreach (var v in sorted)
            {
                string vs = v.ToString();
                output = String.Concat(output, vs," ");
            }

            output.Trim();

            r.Numbers=output;
            var elapsedMs = (double) elapsedTicks / Stopwatch.Frequency * 1000;
            r.TimeToSort = elapsedMs;
            svc.AddRecord(r);

            Alert("Numbers successfully sorted & added to database!", AlertType.success);

            return View(nameof(GetRecord),r );
        }
    }
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item active" aria-current="page">Home</li>
    </ol>
</nav>

<div class="jumbotron jumbotron-fluid">
    <div class="container">
        <h1 class="display-4">Home page</h1>
        <p class="lead">This is the home page of the project.</p>

        <hr class="my-4">
        <p>Please click Data to view numbers in the database.</p>
        <p>Alternatively, please click Add Numbers to add numbers to the database.</p>

    </div>
</div>

<div class="text">
    <br />

    <a class="btn btn-primary" asp-controller="Record" asp-action="Create">Add Numbers</a>
</div>

WebApplication1/Views/Record/Create.cshtml
@model Record

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Add Numbers</li>
    </ol>
</nav>


<h2>Add Numbers</h2>

<form asp-action="Create">

    <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Numbers" class="control-label"></label>
        <textarea rows="5" asp-for="Numbers" class="form-control"></textarea>
        <span asp-validation-for="Numbers" class="text-danger"></span>
    </div>

    <div class="row">
        <div class="col">
            <label asp-for="Order" class="control-label"></label>
            <select asp-for="Order" asp-items="Html.GetEnumSelectList<Order>()" class="form-control">
                <option>Select Order</option>
            </select>
            <span asp-validation-for="Order" class="text-danger"></span>
        </div>
    </div>

    <br />

    <div class="form-group">
        <input type="submit" value="Save" class="btn btn-primary" />
        <a class="btn btn-secondary" asp-action="Index">Cancel</a>
    </div>

</form>

WebApplication1/Views/Record/GetRecord.cshtml
@model Record


<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index" >Home</a></li>
        <li class="breadcrumb-item"><a asp-controller="Record" asp-action="Index" asp-route-order="Ascending">Data</a></li>
        <li class="breadcrumb-item active" aria-current="page">Numbers</li>
    </ol>
</nav>

<br />

<h2>Ordered numbers:</h2>

<br />

<p>@Model.Numbers</p>

WebApplication1/Views/Record/Index.cshtml
@model IList<Record>

<nav aria-label="breadcrumb">
    <ol class="breadcrumb">
        <li class="breadcrumb-item"><a asp-controller="Home" asp-action="Index">Home</a></li>
        <li class="breadcrumb-item active" aria-current="page">Data</li>
    </ol>
</nav>

<div class="text-center">

    <br />

    <table class="table">
        <thead class="thead-light">

            <tr>
                <th class="text-primary">#</th>
                <th class="text-primary">Numbers (truncated view)</th>
                <th class="text-primary">Sorting time (milliseconds)</th>
                <th class="text-primary">Order of sorting</th>
                <th class="text-primary">     </th>
            </tr>

        </thead>
        <tbody>

            @foreach (var s in Model)
            {
                <tr>
                    <td>@s.Id</td>
                    <td>@s.Numbers.Substring(0, Math.Min(s.Numbers.Length, 30))</td>
                    <td>@s.TimeToSort.ToString().Substring(0, Math.Min(s.TimeToSort.ToString().Length, 20))</td>
                    <td>@s.Order</td>
                    <td><a class="btn btn-primary" asp-controller="Record" asp-action="GetRecord" asp-route-id=@s.Id>View numbers</a></td>
                </tr>
            }
        </tbody>
    </table>
</div>

<br />
<div>
    @{
        if (Model.Count == 0)
        {
            <p><b>There is currently no data to display.</b></p>
        }
    }
</div>
<br />

<div class="text">
    <br />

    <a class="btn btn-primary" asp-controller="Record" asp-action="Create">Add Numbers</a>

    <br /> <br />
    <a class="btn btn-primary" asp-controller="Record" asp-action="Export" asp-route-order="Ascending">Export as XML - Ascending Order</a>
    <a class="btn btn-primary" asp-controller="Record" asp-action="Export" asp-route-order="Descending">Export as XML - Descending Order</a>

</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Erik's Solution</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha256-eSi1q2PG6J7g7ib17yAaWMcrr5GrtohYChqibrV7PBE="/>
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Erik's Solution</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Data
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" asp-controller="Record" asp-action="Index" asp-route-order="Ascending">By sort time - ascending</a>
                                <a class="dropdown-item" asp-controller="Record" asp-action="Index" asp-route-order="Descending">By sort time - descending</a>                               
                            </div>
                        </li>
                    </ul>
                </div>

            </div>
        </nav>
    </header>
    <div class="container">        
        <partial name="_RenderAlert" />
        <main role="main" class="pb-3" >
            @RenderBody()
        </main>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha256-E/V4cWE4qvAeO5MOhjtGtqDzPndRO1LBk8lJ/PR7CA4=">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Shared/_RenderAlert.cshtml
@{
    var message = TempData["Alert.Message"] ?? null;
    var type = TempData["Alert.Type"] ?? null;
}

@if (message!=null)
{
<div class=" alert alert-@type" role="alert">
    @message
</div>
}